### ISSUE TITLE
一名初学者在运行示例的命令行时碰到了一些尴尬的问题，可否请您详细说明一下该如何使用GLCache  TinyLFU  QD-LP S3-FIFO算法

### ISSUE THREAD

**Issue by szisbest** [cacheMon/libCacheSim#11]
Hi Jun Cheng Yang,

I hope this message finds you well. I wanted to express my gratitude for your work on [libCacheSim](https://github.com/cacheMon/libCacheSim) . It has been incredibly helpful for my learning journey.
Recently, I've been trying to reproduce [libCacheSim] for a learning project, and I've encountered an issue when trying . I've gone through the documentation and searched the issues on GitHub, but I haven't been able to find a solution.

root@Samuel:/home/sz/libCacheSim/_build# ./bin/cachesim ../data/trace.vscsi vscsi Tinylfu 1mb,16mb,256mb,8gb
Killed
root@Samuel:/home/sz/libCacheSim/_build# ./bin/cachesim ../data/trace.vscsi vscsi Tinylfu 1mb,1mb,64mb,1gb
Killed
root@Samuel:/home/sz/libCacheSim/_build# ./bin/cachesim ../data/trace.vscsi vscsi QD-LP 1mb,16mb,256mb,8gb
[ERROR] 11-30-2023 05:06:09 cache_init.h:160  (tid=139787099014528): do not support algorithm QD-LP
root@Samuel:/home/sz/libCacheSim/_build# ./bin/cachesim ../data/trace.vscsi vscsi glcache 1mb,16mb,256mb,8gb
[ERROR] 11-30-2023 05:20:52 cache_init.h:160  (tid=139781381510528): do not support algorithm glcache
Aborted

I was wondering if you could offer some guidance or point me in the right direction. Any assistance you could provide would be greatly appreciated.
Thank you so much for your time and consideration. I truly appreciate any insights you can share.

Best regards,
Ze Shi

**Comment by 1a1a11a** [comment]
Thank you for your interest! 

The result `killed` is because it runs out of memory. You need to have at least 16GB of DRAM. 

The algorithm is spelled as QDLP (https://github.com/cacheMon/libCacheSim/blob/64f9eeedd20e2b2cd71f8f4a86ef2bcc2de6bad1/libCacheSim/bin/cachesim/cache_init.h#L128) 

GL-Cache needs to be enabled, as mentioned in your previous issue https://github.com/1a1a11a/libCacheSim/issues/41

**Comment by xuefarmer** [comment]
input "cmake -DENABLE_GL_CACHE=1 ..",  then the error is following:CMake Error at CMakeLists.txt:185 (find_package):
  By not providing "Findxgboost.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "xgboost", but
  CMake did not find one.

  Could not find a package configuration file provided by "xgboost" with any
  of the following names:

    xgboostConfig.cmake
    xgboost-config.cmake

  Add the installation prefix of "xgboost" to CMAKE_PREFIX_PATH or set
  "xgboost_DIR" to a directory containing one of the above files.  If
  "xgboost" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!

**Comment by 1a1a11a** [comment]
You need to install xgboost first. The README has more information that you can follow.

**Comment by xuefarmer** [comment]
I have finished it"cmake -DENABLE_GL_CACHE=1 .. ".but the error still exits: do not suppot algorithm glcache.

**Comment by 1a1a11a** [comment]
You can try to clear the _build directory and recompile it (the compile settings are cached so you must start from a fresh one)

**Comment by xuefarmer** [comment]
> You can try to clear the _build directory and recompile it (the compile settings are cached so you must start from a fresh one)
I clear the _build directory and repeat to execute "cmake .. && make -j"  ,but after executing "cmake" ,warning 

CMake Warning at CMakeLists.txt:338 (add_library):
  Cannot generate a safe runtime search path for target libCacheSim because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libzstd.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.


CMake Warning at libCacheSim/bin/cachesim/CMakeLists.txt:2 (add_executable):
  Cannot generate a safe runtime search path for target cachesim because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libzstd.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.

then if I execute "make -j" ,the error come out  "make: *** No targets specified and no makefile found.  Stop.
"          
I don't know if these has something to do with updating the cmake and gcc versions. I have updated them because the xgboost need higher versions.

**Comment by 1a1a11a** [comment]
It looks like the runtime library has conflicts, you can check which version of the zstd is needed and remove the other one

**Comment by szisbest** [comment]
I express my gratitude to the author and fellow enthusiasts who share my interests. I have successfully executed the program.

**Comment by xuefarmer** [comment]
@szisbest I'm glad to hear about your successful reproduction.I haven't finished reproducing  the project. So I wonder if you could provide more datas,images of the results regarding GL-cache like  other cache algorithms in the readme and the method dealing with the problems to me by my email.

**Comment by szisbest** [comment]
我没有通过脚本安装，通过命令行安装的，今天有些晚了，方便的话可以加微信聊天，明天我工作时间可以与您交流。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月18日(周一) 凌晨0:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cacheMon/libCacheSim] 一名初学者在运行示例的命令行时碰到了一些尴尬的问题，可否请您详细说明一下该如何使用GLCache  TinyLFU  QD-LP S3-FIFO算法 (Issue #11)




 
@szisbest I'm glad to hear about your successful reproduction.I haven't finished reproducing  the project. So I wonder if you could provide more datas,images of the results regarding GL-cache like  other cache algorithms in the readme and the method dealing with the problems to me by my email.

**Comment by xuefarmer** [comment]
@szisbest 好的，我的联系方式是 86 15818429199，你可以通过这个联系方式搜索到我的微信

**Comment by szisbest** [comment]
qdlp缩写正确就可以，glcache需要删除原有的_build，重新构建的时候按照原作者说明的来



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月18日(周一) 上午10:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cacheMon/libCacheSim] 一名初学者在运行示例的命令行时碰到了一些尴尬的问题，可否请您详细说明一下该如何使用GLCache  TinyLFU  QD-LP S3-FIFO算法 (Issue #11)




 
@szisbest 好的，我的联系方式是 86 15818429199，你可以通过这个联系方式搜索到我的微信
