### ISSUE TITLE
Does the libCacheSim support concurrent test?

### ISSUE THREAD

**Issue by ChaosD** [cacheMon/libCacheSim#5]
Hello, I want to test concurrent throughput of my cache eviction algorithm. However, I find that the implemented chained hash table in libCacheSim has no support for concurrency. And, I notice the code in `dataStructure/hashtable/hashtable.h`:

```
#elif HASHTABLE_TYPE == CUCKCOO_HASHTABLE
#include "cuckooHashTable.h"
#error not implemented
#else
#error not implemented
#endif
```

I don't find the header file `cuckooHashTable.h`. Is there any support for libcuckoo?

**Comment by 1a1a11a** [comment]
Hi @ChaosD, there is no support for concurrent caches mostly because they produce non-deterministic results. And different algorithms need different implementations. Also when you want to speed it, you will also need one reader per thread or have a request queue. 
I am interested in adding concurrency and if you are interested in sending a PR, I am happy to chat more.

**Comment by ChaosD** [comment]
This idea sounds interesting. I'll try to create a PR (or more) in the few days.

**Comment by 1a1a11a** [comment]
SG, we would prefer less intrusive changes to existing code, so if you could make a plan in a new issue, that would be much appreciated. :)

**Comment by ChaosD** [comment]
You are right. I will close this issue soon, and create a brief introduction in a new issue. Any suggestion is welcome.
